services:
  postgres:
    image: postgres:17-alpine
    container_name: unicase_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: unicase_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: unicase_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadminpassword"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  # ðŸ‘‡ Ø³Ø±ÙˆÛŒØ³ Ø¬Ø¯ÛŒØ¯: Ø§ÛŒÙ† Ú©Ø§Ù†ØªÛŒÙ†Ø± Ù…Ø³Ø¦ÙˆÙ„ Ø³Ø§Ø®Øª Ø®ÙˆØ¯Ú©Ø§Ø± Ø¨Ø§Ú©Øª Ø§Ø³Øª
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      # 1. ØµØ¨Ø± Ú©Ù† ØªØ§ Ø³Ø±ÙˆÛŒØ³ MinIO Ú©Ø§Ù…Ù„Ø§Ù‹ Ù„ÙˆØ¯ Ø´ÙˆØ¯
      until /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadminpassword; do
        echo '...waiting for minio...';
        sleep 1;
      done;

      # 2. Ø¨Ø§Ú©Øª Ø±Ø§ Ø¨Ø³Ø§Ø² (ignore if exists ÛŒØ¹Ù†ÛŒ Ø§Ú¯Ø± Ø¨ÙˆØ¯ Ø§Ø±ÙˆØ± Ù†Ø¯Ù‡)
      /usr/bin/mc mb --ignore-existing myminio/unicase-media;

      # 3. Ø¯Ø³ØªØ±Ø³ÛŒ Ù¾Ø§Ø¨Ù„ÛŒÚ© Ø¨Ù‡ Ø¢Ù† Ø¨Ø¯Ù‡
      /usr/bin/mc anonymous set public myminio/unicase-media;

      echo 'âœ… Bucket created and set to public!';
      exit 0;
      "

volumes:
  postgres_data:
  minio_data:
