services:
  postgres:
    image: postgres:17-alpine
    container_name: unicase_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: unicase_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: unicase_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadminpassword"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-setup:
    image: minio/mc:latest
    container_name: unicase_mc
    depends_on:
      - minio
    volumes:
      - ./cors.json:/cors.json
    entrypoint: >
      /bin/sh -c "
      echo 'â³ Waiting for MinIO...';
      until /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadminpassword; do
        echo '...waiting...';
        sleep 1;
      done;

      echo 'ğŸš€ Creating bucket...';
      /usr/bin/mc mb --ignore-existing myminio/unicase-media;

      echo 'ğŸ”“ Setting public policy...';
      /usr/bin/mc anonymous set public myminio/unicase-media;

      echo 'âš™ï¸ Setting CORS configuration...';
      /usr/bin/mc cors set myminio/unicase-media /cors.json;

      echo 'âœ… MinIO Ready!';
      exit 0;
      "

volumes:
  postgres_data:
  minio_data:
